#---------------------------------
# Variables are needed to be set, see run_docker_compose.sh
#---------------------------------
version: "3.6"
services:
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001
    networks:
      proximax-ipfs:
        ipv4_address: 10.5.0.7
    volumes:
      - ./ipfs_staging/:/export
      - ./ipfs_data:/data/ipfs
    restart: always
    command: ["daemon", "--migrate=true", "--enable-gc=true"]

  proximax:
    depends_on:
      - ipfs
    image: proximax/proximax-platform-nis1:0.1.0-beta
    ports:
      - "8881:8881"
    networks:
      proximax-ipfs:
        ipv4_address: 10.5.0.6
    environment:
      - STORAGE_URI=/ip4/10.5.0.7/tcp/5001
      - STORAGE_NODES=10.5.0.7
      - STORAGE_GATEWAY_API=/ip4/10.5.0.7/tcp/8080
    volumes:
      - ./config/config.properties:/opt/proximax/config/config.properties


networks:
  proximax-ipfs:
    driver: bridge
    # Static IP address. This is a workaround as Java IPS API multiaddr implementation does not handle DNS e.g. /ip4/ipfs/tcp/5001
    ipam:
     config:
       - subnet: 10.5.0.0/16
